### ISSUE TITLE
registrar.activeContext() must not be null

### ISSUE THREAD

**Issue by dong199101** [yxwandroid/flutter_plugin_record#45]
因为要修改插件源码，所以直接把整个插件导入到工程的，但是会报错
Caused by: java.lang.IllegalStateException: registrar.activeContext() must not be null
07-15 15:48:29.321 25932 25932 E AndroidRuntime:        at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin$Companion.registerWith(FlutterPluginRecordPlugin.kt:36)
07-15 15:48:29.321 25932 25932 E AndroidRuntime:        at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.registerWith(Unknown Source:2)
07-15 15:48:29.321 25932 25932 E AndroidRuntime:        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:19)
07-15 15:48:29.321 25932 25932 E AndroidRuntime:        at com.example.im_kit.MainActivity.onCreate(MainActivity.kt:18)
07-15 15:48:29.321 25932 25932 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7802)
07-15 15:48:29.321 25932 25932 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7791)
07-15 15:48:29.321 25932 25932 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
请问这是registerWith方法flutter版本兼容问题么？

**Comment by yxwandroid** [comment]
你要是需要修改源码的可以进行fork下来然后进行修改 
然后通过如下方式进行引入 

flutter_plugin_record:
    git:
      url: https://github.com/yxwandroid/flutter_plugin_record.git    TODO 替换成你fork的项目地址就行了 

不明白你是怎么把项目导入到你的工程里面的
@dong199101
