### ISSUE TITLE
android 同意权限错误如下

### ISSUE THREAD

**Issue by songjiabin** [yxwandroid/flutter_plugin_record#67]
2020-09-11 14:04:09.624 23298-23298/  E/AndroidRuntime: FATAL EXCEPTION: main
     
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property call has not been initialized
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property call has not been initialized
        at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.initRecord(FlutterPluginRecordPlugin.kt:77)
        at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.onRequestPermissionsResult(FlutterPluginRecordPlugin.kt:340)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:612)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:356)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:509)
        at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:611)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7608)
        at android.app.Activity.dispatchActivityResult(Activity.java:7458)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2020-09-11 14:04:09.632 23298-23651/ D/JIGUANG-JCommon: [JCommonInterface] onEvent action:deviceinfo
2020-09-11 14:04:09.666 1938-2523/? E/memtrack: Couldn't load memtrack module
2020-09-11 14:04:09.666 1938-2523/? W/android.os.Debug: failed to get memory consumption info: -1
2020-09-11 14:04:09.715 23298-23651/ W/  Accessing hidden method Landroid/telephony/TelephonyManager;->getSimCount()I (light greylist, reflection)
2020-09-11 14:04:09.715 23298-23651/ : Accessing hidden method Landroid/telephony/TelephonyManager;->getSimSerialNumber(I)Ljava/lang/String; (light greylist, reflection)
2020-09-11 14:04:09.715 23298-23651/ Accessing hidden method Landroid/telephony/TelephonyManager;->getSubscriberId(I)Ljava/lang/String; (light greylist, reflection)
2020-09-11 14:04:09.715 23298-23651/  Accessing hidden method Landroid/telephony/SubscriptionManager;->getSubId(I)[I (light greylist, reflection)
2020-09-11 14:04:09.721 23298-23651/ : Access denied finding property "vendor.cellular.ril.imsi"
2020-09-11 14:04:09.713 23298-23298/ /jg_fr_pool_thre: type=1400 audit(0.0:45): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=6286 scontext=u:r:untrusted_app:s0:c95,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
2020-09-11 14:04:09.739 1890-2022/? W/SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=132#0
2020-09-11 14:04:09.739 1890-2022/? W/SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - Task=132#0
2020-09-11 14:04:10.329 1938-2179/? I/GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@3f4a369)
2020-09-11 14:04:10.330 1938-1951/? I/GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@3f4a369)
2020-09-11 14:04:10.908 2345-22002/? E/NetRec: [1318] aiwn.a: Error decrypting
    java.security.GeneralSecurityException: Digest not verified
        at aiwf.b(:com.google.android.gms@16089022@16.0.89 (040700-239467275):5)
        at aiwf.b(:com.google.android.gms@16089022@16.0.89 (040700-239467275):9)
        at aiwn.a(:com.google.android.gms@16089022@16.0.89 (040700-239467275):54)
        at aivq.b(:com.google.android.gms@16089022@16.0.89 (040700-239467275):11)
        at aivq.a(:com.google.android.gms@16089022@16.0.89 (040700-239467275):2)
        at aivq.a(:com.google.android.gms@16089022@16.0.89 (040700-239467275):97)
        at com.google.android.gms.netrec.module.NetRecChimeraGcmTaskService.a(:com.google.android.gms@16089022@16.0.89 (040700-239467275):19)
        at zse.run(:com.google.android.gms@16089022@16.0.89 (040700-239467275):5)
        at rrt.b(:com.google.android.gms@16089022@16.0.89 (040700-239467275):32)
        at rrt.run(:com.google.android.gms@16089022@16.0.89 (040700-239467275):21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at rxx.run(Unknown Source:7)
        at java.lang.Thread.run(Thread.java:764)

**Comment by yxwandroid** [comment]
调用init方法了吗 你可以先参考一下example的代码

**Comment by songjiabin** [comment]
调用了，我再试试 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wilson"<notifications@github.com&gt;; 
发送时间: 2020年9月11日(星期五) 下午2:17
收件人: "yxwandroid/flutter_plugin_record"<flutter_plugin_record@noreply.github.com&gt;; 
抄送: "?"<1796254117@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [yxwandroid/flutter_plugin_record] android 同意权限错误如下 (#67)





 
调用init方法了吗 你可以先参考一下example的代码

**Comment by yxwandroid** [comment]
或则直接进qq群反馈 790157613

**Comment by songjiabin** [comment]
找不到群&nbsp;，刚才我试过








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yxwandroid/flutter_plugin_record"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月11日(星期五) 下午2:20
收件人:&nbsp;"yxwandroid/flutter_plugin_record"<flutter_plugin_record@noreply.github.com&gt;;
抄送:&nbsp;"?"<1796254117@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yxwandroid/flutter_plugin_record] android 同意权限错误如下 (#67)





 
或则直接进qq群反馈 790157613

**Comment by yxwandroid** [comment]
加这个群 790157613

**Comment by yxwandroid** [comment]
> 找不到群&nbsp;，刚才我试过
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yxwandroid/flutter_plugin_record" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月11日(星期五) 下午2:20 收件人:&nbsp;"yxwandroid/flutter_plugin_record"<flutter_plugin_record@noreply.github.com&gt;; 抄送:&nbsp;"?"<1796254117@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [yxwandroid/flutter_plugin_record] android 同意权限错误如下 (#67) 或则直接进qq群反馈 790157613 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你重新在添加试试

**Comment by yxwandroid** [comment]
> 找不到群&nbsp;，刚才我试过
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yxwandroid/flutter_plugin_record" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月11日(星期五) 下午2:20 收件人:&nbsp;"yxwandroid/flutter_plugin_record"<flutter_plugin_record@noreply.github.com&gt;; 抄送:&nbsp;"?"<1796254117@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [yxwandroid/flutter_plugin_record] android 同意权限错误如下 (#67) 或则直接进qq群反馈 790157613 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你重新在添加试试

**Comment by popularlzp** [comment]
[setting设备.txt](https://github.com/yxwandroid/flutter_plugin_record/files/5941774/setting.txt)

**Comment by popularlzp** [comment]
[Uploading manifest-merger-debug-report.txt…]()

**Comment by popularlzp** [comment]
[Uploading manifest-merger-debug-report.txt…]()

**Comment by popularlzp** [comment]
tv_setting_time
[Uploading manifest-merger-debug-report.txt…]()
