### ISSUE TITLE
Supporting the new Android plugins

### ISSUE THREAD

**Issue by songshitong** [yxwandroid/flutter_plugin_record#73]
please  support the new Android plugins

document  https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

in android embedding v2 , plugin will be crash

`java.lang.IllegalStateException: registrar.activeContext() must not be null
E/AndroidRuntime(31785): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3501)
E/AndroidRuntime(31785): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3661)
E/AndroidRuntime(31785): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(31785): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(31785): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(31785): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2108)
E/AndroidRuntime(31785): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31785): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(31785): 	at android.app.ActivityThread.main(ActivityThread.java:7876)
E/AndroidRuntime(31785): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31785): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime(31785): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
E/AndroidRuntime(31785): Caused by: java.lang.IllegalStateException: registrar.activeContext() must not be null
E/AndroidRuntime(31785): 	at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin$Companion.registerWith(FlutterPluginRecordPlugin.kt:41)
E/AndroidRuntime(31785): 	at record.wilson.flutter.com.flutter_plugin_record.FlutterPluginRecordPlugin.registerWith(Unknown Source:2)
E/AndroidRuntime(31785): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:24)
E/AndroidRuntime(31785): 	at com.cen.gwadarpro.MainActivity.configureFlutterEngine(MainActivity.kt:12)
E/AndroidRuntime(31785): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/AndroidRuntime(31785): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:411)
E/AndroidRuntime(31785): 	at android.app.Activity.performCreate(Activity.java:8093)
E/AndroidRuntime(31785): 	at android.app.Activity.performCreate(Activity.java:8067)
E/AndroidRuntime(31785): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
E/AndroidRuntime(31785): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3474)
E/AndroidRuntime(31785): 	... 11 more`

**Comment by songshitong** [comment]
I create a pull request for [this](https://github.com/yxwandroid/flutter_plugin_record/pull/74)
