### ISSUE TITLE
录制MP3报错

### ISSUE THREAD

**Issue by yhw-lkdmk** [yxwandroid/flutter_plugin_record#96]
E/FFmpeg  ( 8127): Exception while trying to run: [Ljava.lang.String;@72679ee
E/FFmpeg  ( 8127): java.io.IOException: Cannot run program "/data/user/0/com.example.haoyuit_app_student/files/ffmpeg": error=13, Permission denied
E/FFmpeg  ( 8127):      at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
E/FFmpeg  ( 8127):      at java.lang.Runtime.exec(Runtime.java:698)
E/FFmpeg  ( 8127):      at java.lang.Runtime.exec(Runtime.java:563)
E/FFmpeg  ( 8127):      at com.github.hiteshsondhi88.libffmpeg.ShellCommand.run(ShellCommand.java:10)
E/FFmpeg  ( 8127):      at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:38)
E/FFmpeg  ( 8127):      at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)
E/FFmpeg  ( 8127):      at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/FFmpeg  ( 8127):      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FFmpeg  ( 8127):      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/FFmpeg  ( 8127):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FFmpeg  ( 8127):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FFmpeg  ( 8127):      at java.lang.Thread.run(Thread.java:919)
E/FFmpeg  ( 8127): Caused by: java.io.IOException: error=13, Permission denied
E/FFmpeg  ( 8127):      at java.lang.UNIXProcess.forkAndExec(Native Method)
E/FFmpeg  ( 8127):      at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
E/FFmpeg  ( 8127):      at java.lang.ProcessImpl.start(ProcessImpl.java:141)
E/FFmpeg  ( 8127):      at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
E/FFmpeg  ( 8127):      ... 11 more
D/android ( 8127):   ConvertCallback java.io.IOException:

**Comment by shijianmei** [comment]
the same quetion
